name: ${project.name}
main: es.kikisito.nfcnotes.Main
version: ${project.version}
api-version: 1.13
softdepend: [Vault, Essentials, PlayerPoints]
author: Kikisito
folia-supported: true
commands:
  withdraw:
    description: Withdraw your money
    aliases:
      - cheque
  createnote:
    description: Create a note
    aliases:
      - cn
  nfcnotes:
    description: Plugin information
  deposit:
    description: Deposit money
  count:
    description: Check how much money does the inventory of a player have
permissions:
  # Withdraw permissions
  nfcnotes.withdraw.*:
    description: Allows you to withdraw money
    default: true
    children:
      nfcnotes.withdraw.one: true
      nfcnotes.withdraw.all: true
      nfcnotes.withdraw.multiple: true
  nfcnotes.withdraw.one:
    description: Allows you to withdraw one note per command.
    default: true
  nfcnotes.withdraw.all:
    description: Allows you to withdraw all your money using "all" instead of a number.
    default: true
  nfcnotes.withdraw.multiple:
    description: Allows you to withdraw multiples notes at once.
    default: true

  # Deposit permissions
  nfcnotes.deposit.*:
    description: Allows you to deposit money back into your account using all possible methods
    default: true
    children:
      nfcnotes.deposit.action: true
      nfcnotes.deposit.command: true
  nfcnotes.deposit.action:
    description: Allows you to deposit money back into your account using right click
    default: true
    children:
      nfcnotes.deposit.action.deposit: true
      nfcnotes.deposit.massdeposit: true
    nfcnotes.deposit.action.deposit:
      description: Allows you to deposit a note into your account
      default: true
  nfcnotes.deposit.massdeposit:
    description: Allows you to deposit all your notes back into your account
    default: true
  nfcnotes.deposit.command.*:
    description: Allows you to use all deposit commands.
    default: true
    children:
      nfcnotes.deposit.command.one: true
      nfcnotes.deposit.command.all: true
      nfcnotes.deposit.command.multiple: true
      nfcnotes.deposit.command.stack: true
  nfcnotes.deposit.command.one:
    description: Allows you to deposit money back into your account using /deposit command
    default: true
  nfcnotes.deposit.command.multiple:
    description: Allows you to deposit multiple notes back into your account using /deposit command
    default: true
  nfcnotes.deposit.command.all:
    description: Allows you to deposit all your notes
    default: true
  nfcnotes.deposit.command.stack:
    description: Allows you to deposit the stack of notes you're holding.
    default: true

  # Count permissions
  nfcnotes.count.*:
    description: Allows you to use all count subcommands (excluding the staff ones)
    default: true
    children:
      nfcnotes.count.self: true
  nfcnotes.count.self:
    description: Allows you to see how much money you have in your inventory
    default: true

  # Staff permissions
  nfcnotes.staff.*:
    description: Allows you to use any staff command
    default: op
    children:
      nfcnotes.staff.warn: true
      nfcnotes.staff.createnote: true
      nfcnotes.staff.reload: true
      nfcnotes.staff.check-updates: true
      nfcnotes.staff.deposit.bypass.disabled-world: true
      nfcnotes.staff.withdraw.bypass.disabled-world: true
  nfcnotes.staff.warn:
    description: Warns you when a player withdraws or deposits a large amount of money
    default: op
  nfcnotes.staff.createnote:
    description: Create a note
    default: op
  nfcnotes.staff.reload:
    description: Create a note
    default: op
  nfcnotes.staff.check-updates:
    description: Allows the user to check if the plugin is up to date
    default: op
  nfcnotes.staff.withdraw.bypass.disabled-world:
    description: Bypass disabled world restriction. Withdraw only.
    default: op
  nfcnotes.staff.deposit.bypass.disabled-world:
    description: Bypass disabled world restriction. Deposit only.
    default: op
  nfcnotes.staff.count.others:
    description: Allows you to see how much money has a player in their inventory
    default: op